proxies:
- name: "\U0001F1F3\U0001F1F1 The Netherlands — #306"
  type: "vless"
  server: "45.151.62.149"
  port: 443
  uuid: "218fd696-e3a2-4c33-b397-a5f13a82969e"
  udp: true
  skip-cert-verify: true
  network: "grpc"
  tls: true
  servername: "www.aviasales.com"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "aBs0x09cXtjTpsrGb21cJsEmDsaCaC1RPeutNu404V0"
    short-id: "6fa13cdb"
  grpc-opts:
    grpc-service-name: "grpc"
- name: "\U0001F1EB\U0001F1EE Finland — #220"
  type: "vless"
  server: "194.55.239.87"
  port: 8444
  uuid: "c7b01766-fe25-412c-b128-f939d1626729"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "manage.rushtaxi.ru"
  client-fingerprint: "safari"
  reality-opts:
    public-key: "Skfx5UvBjoad_PuuLRXcE1quXaTbRcB0kAk1YP0UwnQ"
- name: "\U0001F1EB\U0001F1EE Finland — #229"
  type: "vless"
  server: "194.55.239.87"
  port: 8444
  uuid: "c7b01766-fe25-412c-b128-f939d1626729"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "manage.rushtaxi.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "Skfx5UvBjoad_PuuLRXcE1quXaTbRcB0kAk1YP0UwnQ"
- name: "\U0001F1F7\U0001F1FA Timeweb — #36"
  type: "vless"
  server: "194.55.239.174"
  port: 443
  uuid: "2c634977-584e-4e1f-b501-1b70c77a6743"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: true
  servername: "furrycdn.net"
  client-fingerprint: "qq"
  ws-opts:
    path: "/api/v1/video-stream"
- name: "\U0001F1EB\U0001F1EE Finland — #155"
  type: "vless"
  server: "194.55.239.87"
  port: 8444
  uuid: "c7b01766-fe25-412c-b128-f939d1626729"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "manage.rushtaxi.ru"
  client-fingerprint: "safari"
  reality-opts:
    public-key: "Skfx5UvBjoad_PuuLRXcE1quXaTbRcB0kAk1YP0UwnQ"
- name: "\U0001F1EB\U0001F1EE Finland — #156"
  type: "vless"
  server: "194.55.239.87"
  port: 8444
  uuid: "c7b01766-fe25-412c-b128-f939d1626729"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "manage.rushtaxi.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "Skfx5UvBjoad_PuuLRXcE1quXaTbRcB0kAk1YP0UwnQ"
- name: "\U0001F1F7\U0001F1FA Timeweb — #27"
  type: "vless"
  server: "194.55.239.174"
  port: 443
  uuid: "2c634977-584e-4e1f-b501-1b70c77a6743"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: true
  servername: "furrycdn.net"
  client-fingerprint: "chrome"
  ws-opts:
    path: "/api/v1/video-stream"
    headers:
      Host: "furrycdn.net"
- name: "\U0001F1E9\U0001F1EA Germany — #29"
  type: "vless"
  server: "147.45.253.97"
  port: 4100
  uuid: "9b44bfb4-9d28-4870-9fc3-5154d6d462ff"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
    headers:
      Host: "live.ok.ru"
- name: "\U0001F1F7\U0001F1FA Timeweb — #28"
  type: "vless"
  server: "194.55.239.174"
  port: 443
  uuid: "2c634977-584e-4e1f-b501-1b70c77a6743"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: true
  servername: "furrycdn.net"
  client-fingerprint: "chrome"
  ws-opts:
    path: "/api/v1/video-stream"
- name: "\U0001F1F7\U0001F1FA 4vps.su — #2"
  type: "vless"
  server: "45.143.203.21"
  port: 443
  uuid: "3e7f67de-648e-4871-b51a-a225214d41ee"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  tls: true
  servername: "j.6sc.co"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "TRP10HqKUXEQ3O-cfsq93DycfBmbJe9KM36yvSa8Mmw"
- name: "\U0001F1E9\U0001F1EA Germany — #40"
  type: "vless"
  server: "130.17.2.28"
  port: 2200
  uuid: "9501f3d6-483f-45c1-ab2c-33266520cd5c"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
    headers:
      Host: "rzd.ru"
- name: "\U0001F1E9\U0001F1EA Germany — #43"
  type: "vless"
  server: "130.17.2.49"
  port: 2200
  uuid: "d4aad26f-70b6-4411-8517-17f7b4281886"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1E9\U0001F1EA Germany — #44"
  type: "vless"
  server: "89.127.217.98"
  port: 4100
  uuid: "9b44bfb4-9d28-4870-9fc3-5154d6d462ff"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
    headers:
      Host: "live.ok.ru"
- name: "\U0001F1E9\U0001F1EA Germany — #48"
  type: "vless"
  server: "89.127.197.71"
  port: 2200
  uuid: "9b44bfb4-9d28-4870-9fc3-5154d6d462ff"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1E9\U0001F1EA Germany — #50"
  type: "vless"
  server: "89.127.217.210"
  port: 2200
  uuid: "9501f3d6-483f-45c1-ab2c-33266520cd5c"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1E9\U0001F1EA Germany — #51"
  type: "vless"
  server: "81.85.78.78"
  port: 2200
  uuid: "9501f3d6-483f-45c1-ab2c-33266520cd5c"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
    headers:
      Host: "rzd.ru"
- name: "\U0001F1F7\U0001F1FA Timeweb — #19"
  type: "vless"
  server: "194.55.239.174"
  port: 443
  uuid: "2c634977-584e-4e1f-b501-1b70c77a6743"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: true
  servername: "furrycdn.net"
  client-fingerprint: "chrome"
  ws-opts:
    path: "/api/v1/video-stream"
- name: "\U0001F1E9\U0001F1EA Germany — #33"
  type: "vless"
  server: "147.45.253.97"
  port: 4100
  uuid: "9b44bfb4-9d28-4870-9fc3-5154d6d462ff"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1E9\U0001F1EA Germany — #34"
  type: "vless"
  server: "168.222.140.233"
  port: 2200
  uuid: "d4aad26f-70b6-4411-8517-17f7b4281886"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1E9\U0001F1EA Germany — #35"
  type: "vless"
  server: "93.77.188.102"
  port: 443
  uuid: "cad59ee8-e80f-4d0f-a9dd-d082e00a75e4"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "wde3.whitedeu.org"
  client-fingerprint: "ios"
- name: "\U0001F1E9\U0001F1EA Germany — #31"
  type: "vless"
  server: "93.77.188.102"
  port: 443
  uuid: "cad59ee8-e80f-4d0f-a9dd-d082e00a75e4"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "wde3.whitedeu.org"
  client-fingerprint: "edge"
- name: "\U0001F1E9\U0001F1EA Germany — #28"
  type: "vless"
  server: "171.22.134.207"
  port: 443
  uuid: "218fd696-e3a2-4c33-b397-a5f13a82969e"
  udp: true
  skip-cert-verify: true
  network: "grpc"
  tls: true
  servername: "media2.tcpdoor.net"
  client-fingerprint: "ios"
  reality-opts:
    public-key: "vxhkDXfYpz1OLqZ-_9QVoQr3_UJLtJFheb5bD5YH7z8"
    short-id: "3303c7a5"
  grpc-opts:
    grpc-service-name: "grpc"
- name: "\U0001F1E9\U0001F1EA Germany — #16"
  type: "vless"
  server: "130.17.2.66"
  port: 4100
  uuid: "9b44bfb4-9d28-4870-9fc3-5154d6d462ff"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
    headers:
      Host: "live.ok.ru"
- name: "\U0001F1F1\U0001F1FB Latvia — #191"
  type: "vless"
  server: "51.250.82.165"
  port: 443
  uuid: "15e0833c-08ad-47f3-bf80-60c2a47a6774"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "api-maps.yandex.ru"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "KEZ93Y9VgoirI18wIpcfS3z8I9GiaiFe-GKqGdEPMmg"
    short-id: "4e07408562be"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #19"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #16"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #14"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA PJSC VimpelCom — #20"
  type: "vless"
  server: "78.159.250.151"
  port: 2027
  uuid: "db72616a-517a-4673-b424-8c63181a8a08"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "ads.x5.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "EApxy12MeXpqt-78odxizwcXT6hX9f8XeAcbMDVRAV0"
    short-id: "6ba7b8109dad11d1"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #17"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA PJSC VimpelCom — #18"
  type: "vless"
  server: "78.159.250.151"
  port: 2027
  uuid: "db72616a-517a-4673-b424-8c63181a8a08"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "ads.x5.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "EApxy12MeXpqt-78odxizwcXT6hX9f8XeAcbMDVRAV0"
    short-id: "6ba7b8109dad11d1"
- name: "\U0001F1F7\U0001F1FA PJSC VimpelCom — #17"
  type: "vless"
  server: "78.159.250.151"
  port: 2027
  uuid: "db72616a-517a-4673-b424-8c63181a8a08"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "ads.x5.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "EApxy12MeXpqt-78odxizwcXT6hX9f8XeAcbMDVRAV0"
    short-id: "6ba7b8109dad11d1"
- name: "\U0001F1F7\U0001F1FA Spaceweb testing — #24"
  type: "vless"
  server: "77.222.46.162"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #179"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
    spider-x: "/"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #196"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
    spider-x: "/"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #197"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "edge"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #198"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "edge"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
    spider-x: "/"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #199"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
    spider-x: "/"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #21"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #26"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #266"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
    spider-x: "/"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #23"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA Spaceweb testing — #31"
  type: "vless"
  server: "77.222.46.162"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #22"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA Spaceweb testing — #32"
  type: "vless"
  server: "77.222.46.162"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA MegaMax Network — #20"
  type: "vless"
  server: "212.67.9.113"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA PJSC VimpelCom — #21"
  type: "vless"
  server: "78.159.250.151"
  port: 2027
  uuid: "db72616a-517a-4673-b424-8c63181a8a08"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "ads.x5.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "EApxy12MeXpqt-78odxizwcXT6hX9f8XeAcbMDVRAV0"
    short-id: "6ba7b8109dad11d1"
- name: "\U0001F1F7\U0001F1FA Spaceweb testing — #28"
  type: "vless"
  server: "77.222.46.162"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F1\U0001F1FB Latvia — #220"
  type: "vless"
  server: "51.250.82.165"
  port: 443
  uuid: "15e0833c-08ad-47f3-bf80-60c2a47a6774"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "api-maps.yandex.ru"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "KEZ93Y9VgoirI18wIpcfS3z8I9GiaiFe-GKqGdEPMmg"
    short-id: "4e07408562be"
    spider-x: "/"
- name: "\U0001F1F7\U0001F1FA Timeweb — #18"
  type: "vless"
  server: "194.55.239.174"
  port: 443
  uuid: "2c634977-584e-4e1f-b501-1b70c77a6743"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: true
  servername: "furrycdn.net"
  client-fingerprint: "firefox"
  ws-opts:
    path: "/api/v1/video-stream"
- name: "\U0001F1F1\U0001F1FB Latvia — #217"
  type: "vless"
  server: "51.250.82.165"
  port: 443
  uuid: "15e0833c-08ad-47f3-bf80-60c2a47a6774"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "api-maps.yandex.ru"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "KEZ93Y9VgoirI18wIpcfS3z8I9GiaiFe-GKqGdEPMmg"
    short-id: "4e07408562be"
    spider-x: "/"
- name: "\U0001F1F7\U0001F1FA Spaceweb testing — #26"
  type: "vless"
  server: "77.222.46.162"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F7\U0001F1FA Spaceweb testing — #19"
  type: "vless"
  server: "77.222.46.162"
  port: 2200
  uuid: "2aa7f4b1-e859-46d0-b8ac-8587811ab7b1"
  udp: true
  skip-cert-verify: true
  network: "ws"
  tls: false
  ws-opts:
    path: "/v1"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #191"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "chrome"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
    spider-x: "/"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F0\U0001F1FF Kazakhstan — #192"
  type: "vless"
  server: "82.202.158.188"
  port: 544
  uuid: "b440a476-e65e-4f67-9993-b8c6d1308fd7"
  udp: true
  skip-cert-verify: true
  network: "xhttp"
  tls: true
  servername: "www.amd.com"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "xP3LIJ6-qQ51S89vFyW2PQeCjN921yVjN7pFDWKaswU"
    short-id: "1111"
    spider-x: "/"
  xhttp-opts:
    path: "/"
- name: "\U0001F1F1\U0001F1FB Latvia — #197"
  type: "vless"
  server: "51.250.82.165"
  port: 443
  uuid: "15e0833c-08ad-47f3-bf80-60c2a47a6774"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "api-maps.yandex.ru"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "KEZ93Y9VgoirI18wIpcfS3z8I9GiaiFe-GKqGdEPMmg"
    short-id: "4e07408562be"
    spider-x: "/"
- name: "\U0001F1F1\U0001F1FB Latvia — #198"
  type: "vless"
  server: "51.250.82.165"
  port: 443
  uuid: "15e0833c-08ad-47f3-bf80-60c2a47a6774"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "api-maps.yandex.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "KEZ93Y9VgoirI18wIpcfS3z8I9GiaiFe-GKqGdEPMmg"
    short-id: "4e07408562be"
    spider-x: "/"
- name: "\U0001F1F1\U0001F1FB Latvia — #189"
  type: "vless"
  server: "51.250.82.165"
  port: 443
  uuid: "15e0833c-08ad-47f3-bf80-60c2a47a6774"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "api-maps.yandex.ru"
  client-fingerprint: "qq"
  reality-opts:
    public-key: "KEZ93Y9VgoirI18wIpcfS3z8I9GiaiFe-GKqGdEPMmg"
    short-id: "4e07408562be"
    spider-x: "/"
- name: "\U0001F1F1\U0001F1FB Latvia — #190"
  type: "vless"
  server: "51.250.82.165"
  port: 443
  uuid: "15e0833c-08ad-47f3-bf80-60c2a47a6774"
  udp: true
  skip-cert-verify: true
  network: "tcp"
  flow: "xtls-rprx-vision"
  tls: true
  servername: "api-maps.yandex.ru"
  client-fingerprint: "firefox"
  reality-opts:
    public-key: "KEZ93Y9VgoirI18wIpcfS3z8I9GiaiFe-GKqGdEPMmg"
    short-id: "4e07408562be"
    spider-x: "/"
