proxies:
- name: '🇷🇺 GIR SER — #30'
  type: 'vless'
  server: '178.154.243.251'
  port: 443
  uuid: 'bd6acaa8-4579-3d31-9bcb-0dae59f756e9'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  tls: true
  servername: 'www.google.com'
  client-fingerprint: 'random'
  reality-opts:
    public-key: 'JkiFzvTq6FFDb44V8ifby6-P7QZo7Z1B5VOrGTgAQEY'
    short-id: 'a1e1a7'
- name: '🇷🇺 GIR SER — #15'
  type: 'vless'
  server: '178.154.243.251'
  port: 443
  uuid: 'bd6acaa8-4579-3d31-9bcb-0dae59f756e9'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  tls: true
  servername: 'www.google.com'
  client-fingerprint: 'random'
  reality-opts:
    public-key: 'JkiFzvTq6FFDb44V8ifby6-P7QZo7Z1B5VOrGTgAQEY'
    short-id: 'a1e1a7'
- name: '🇷🇺 GIR SER — #16'
  type: 'vless'
  server: '158.160.250.45'
  port: 443
  uuid: 'b6083a84-80a5-3e88-9dbb-5c8ef241be3a'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  tls: true
  servername: 'ads.x5.ru'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'mDtiIWLFPJoPVrDLOCvKn6lvlS8r0TdRO9MxmmdIDmo'
    short-id: '917fd5a45e8840'
- name: '🇷🇺 GIR SER — #17'
  type: 'vless'
  server: '178.154.243.251'
  port: 443
  uuid: 'bd6acaa8-4579-3d31-9bcb-0dae59f756e9'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  tls: true
  servername: 'www.google.com'
  client-fingerprint: 'random'
  reality-opts:
    public-key: 'JkiFzvTq6FFDb44V8ifby6-P7QZo7Z1B5VOrGTgAQEY'
    short-id: 'a1e1a7'
