proxies:
- name: '🇩🇪 Germany — #24'
  type: 'vless'
  server: '185.218.0.41'
  port: 2096
  uuid: 'd9228d5d-618d-4771-835f-96b4ebdd38cd'
  udp: true
  skip-cert-verify: true
  network: 'grpc'
  tls: true
  servername: 'id.vk.com'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
  grpc-opts:
    grpc-service-name: 'vless-grpc-reality'
- name: '🇩🇪 Germany — #25'
  type: 'vless'
  server: '185.72.144.177'
  port: 2096
  uuid: 'd9228d5d-618d-4771-835f-96b4ebdd38cd'
  udp: true
  skip-cert-verify: true
  network: 'grpc'
  tls: true
  servername: 'id.vk.com'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
  grpc-opts:
    grpc-service-name: 'vless-grpc-reality'
- name: '🇩🇪 Germany — #26'
  type: 'vless'
  server: '185.251.89.9'
  port: 2096
  uuid: 'd9228d5d-618d-4771-835f-96b4ebdd38cd'
  udp: true
  skip-cert-verify: true
  network: 'grpc'
  tls: true
  servername: 'id.vk.com'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
  grpc-opts:
    grpc-service-name: 'vless-grpc-reality'
- name: '🇩🇪 Germany — #27'
  type: 'vless'
  server: '185.251.91.184'
  port: 2096
  uuid: 'd9228d5d-618d-4771-835f-96b4ebdd38cd'
  udp: true
  skip-cert-verify: true
  network: 'grpc'
  tls: true
  servername: 'id.vk.com'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
  grpc-opts:
    grpc-service-name: 'vless-grpc-reality'
- name: '🇩🇪 Germany — #28'
  type: 'vless'
  server: '185.251.91.184'
  port: 2096
  uuid: 'd9228d5d-618d-4771-835f-96b4ebdd38cd'
  udp: true
  skip-cert-verify: true
  network: 'grpc'
  tls: true
  servername: 'id.vk.com'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
  grpc-opts:
    grpc-service-name: 'vless-grpc-reality'
- name: '🇩🇪 Germany — #30'
  type: 'vless'
  server: '185.218.0.41'
  port: 2096
  uuid: 'd9228d5d-618d-4771-835f-96b4ebdd38cd'
  udp: true
  skip-cert-verify: true
  network: 'grpc'
  tls: true
  servername: 'id.vk.com'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
  grpc-opts:
    grpc-service-name: 'vless-grpc-reality'
- name: '🇩🇪 Germany — #31'
  type: 'vless'
  server: '185.251.89.9'
  port: 2096
  uuid: 'd9228d5d-618d-4771-835f-96b4ebdd38cd'
  udp: true
  skip-cert-verify: true
  network: 'grpc'
  tls: true
  servername: 'id.vk.com'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
  grpc-opts:
    grpc-service-name: 'vless-grpc-reality'
- name: '🇩🇪 Germany — #15'
  type: 'vless'
  server: '37.139.34.124'
  port: 443
  uuid: 'ae0959f1-f25a-43d0-9c88-be1672641fc3'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  flow: 'xtls-rprx-vision'
  tls: true
  servername: 'ads.x5.ru'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'FOVEr4SzLDQGUn1yY8-Y_C5mIV6WBJL2sTZKQvK83z4'
- name: '🇩🇪 Germany — #16'
  type: 'vless'
  server: '37.139.34.124'
  port: 443
  uuid: 'ae0959f1-f25a-43d0-9c88-be1672641fc3'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  flow: 'xtls-rprx-vision'
  tls: true
  servername: 'ads.x5.ru'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'FOVEr4SzLDQGUn1yY8-Y_C5mIV6WBJL2sTZKQvK83z4'
- name: '🇩🇪 Germany — #23'
  type: 'vless'
  server: '178.250.242.39'
  port: 443
  uuid: '7573908b-d981-4153-92aa-33ee2d22144c'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  tls: true
  servername: 'www.kinopoisk.ru'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'VH-4z1TvkJLyH9cgwdrhvMevxr3PltSBnMk43X6pi2U'
    short-id: '086007'
    spider-x: '/'
- name: '🇩🇪 Germany — #17'
  type: 'vless'
  server: '178.250.242.39'
  port: 443
  uuid: '7573908b-d981-4153-92aa-33ee2d22144c'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  tls: true
  servername: 'www.kinopoisk.ru'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'VH-4z1TvkJLyH9cgwdrhvMevxr3PltSBnMk43X6pi2U'
    short-id: '086007'
- name: '🇦🇹 Austria — #28'
  type: 'vless'
  server: '95.163.211.206'
  port: 443
  uuid: 'b2b8bd00-2e42-4875-8d7b-bcf97093a1d4'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  flow: 'xtls-rprx-vision'
  tls: true
  servername: 'at.sellflow.org'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
- name: '🇩🇪 Germany — #14'
  type: 'vless'
  server: '37.139.34.124'
  port: 443
  uuid: 'ae0959f1-f25a-43d0-9c88-be1672641fc3'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  flow: 'xtls-rprx-vision'
  tls: true
  servername: 'ads.x5.ru'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'FOVEr4SzLDQGUn1yY8-Y_C5mIV6WBJL2sTZKQvK83z4'
- name: '🇩🇪 Germany — #10'
  type: 'vless'
  server: '178.250.242.39'
  port: 443
  uuid: '7573908b-d981-4153-92aa-33ee2d22144c'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  tls: true
  servername: 'www.kinopoisk.ru'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'VH-4z1TvkJLyH9cgwdrhvMevxr3PltSBnMk43X6pi2U'
    short-id: '086007'
    spider-x: '/'
- name: '🇩🇪 Germany — #12'
  type: 'vless'
  server: '37.139.34.124'
  port: 443
  uuid: 'ae0959f1-f25a-43d0-9c88-be1672641fc3'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  flow: 'xtls-rprx-vision'
  tls: true
  servername: 'ads.x5.ru'
  client-fingerprint: 'chrome'
  reality-opts:
    public-key: 'FOVEr4SzLDQGUn1yY8-Y_C5mIV6WBJL2sTZKQvK83z4'
- name: '🇦🇹 Austria — #12'
  type: 'vless'
  server: '95.163.211.206'
  port: 443
  uuid: 'b2b8bd00-2e42-4875-8d7b-bcf97093a1d4'
  udp: true
  skip-cert-verify: true
  network: 'tcp'
  flow: 'xtls-rprx-vision'
  tls: true
  servername: 'at.sellflow.org'
  client-fingerprint: 'firefox'
  reality-opts:
    public-key: 'SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc'
